# Generated by Django 5.0.6 on 2024-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_created_at_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=10),
        ),
    ]
